config/routes.rb
MaxHouse::Application.routes.draw do

  namespace :admin do
    resources :dogs
  end

  resources :breeds
  resources :dogs
  
  match 'auth/provider/callback' => 'sessions#create'
  match 'auth/failure' => redirect('/')
  match 'signout' => 'sessions#destroy', as: 'signout'

  root :to => 'welcome#index'

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :dogs
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :breed
  attr_accessible :age, :name, :nickname

  def self.top_three
    Dog.first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :oauth_expires_at, :oauth_token, :provider, :uid

  def self.find_or_initialize_from_omniauth(auth)
    Rails.logger.info(auth)    
  end
end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController
  respond_to :html, :json

  def index
    @dogs = Dog.all
    respond_with @dogs
  end

  def show
    @dog = Dog.find(params[:id])
    respond_with @dogs
  end

  def new
    @dog = Dog.new
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def create
    @dog = Dog.new(params[:admin_dog])
    respond_with @dog
  end

  def update
    @dog = Dog.find(params[:id])
    respond_with @dog
  end

  def destroy
    @dog = Admin::Dog.find(params[:id])
    @dog.destroy
    respond_with @dog
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  def create
    user = User.find_or_initialize(auth)
    session[:user_id] = user.user_id
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  #  @dogs = ["Max", "Doug", "Rose"]
  end
end

app/helpers/admin/dogs_helper.rb
module Admin::DogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dogs/_form.html.haml
= form_for [:admin, @dog], {class: 'form-horizontal'} do |f|
  %fieldset
    %legend Some basic info
  - if @dog.errors.any?
    #error_explanation
      %ul
        - @dog.errors.full_messages.each do |msg|
          %li= msg

  .control-group
    %label.control-label Name
    .controls= f.text_field 'name'

  .control-group
    %label.control-label Nickname
    .controls= f.text_field 'nickname'

  .control-group
    %label.control-label Breed
    .controls= f.select :breed_id, Breed.all.map{|breed| [breed.name, breed.id]}

  .control-group
    .controls= f.submit 'Save', class: 'btn primary'

app/views/admin/dogs/edit.html.haml
%h1 Editing admin_dog

= render 'form'

= link_to 'Show', @admin_dog
\|
= link_to 'Back', admin_dogs_path

app/views/admin/dogs/index.html.haml
%h1 Dog Listing

%table
  %tr
    %th
    %th
    %th

  - @dogs.each do |admin_dog|
    %tr
      %td= link_to 'Show', admin_dog
      %td= link_to 'Edit', edit_admin_dog_path(admin_dog)
      %td= link_to 'Destroy', admin_dog, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Dog', new_admin_dog_path

app/views/admin/dogs/new.html.haml
%h1 Add a new Doggy

= render 'form'

= link_to 'Back', admin_dogs_path

app/views/admin/dogs/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_dog_path(@admin_dog)
\|
= link_to 'Back', admin_dogs_path

app/views/breeds/index.html.haml
%h1 All the breeds in Max House
.hero-unit
  #hero1
    %h1 Max
    %p  Here is my description
    #panel-links
      %span.bagde.badge-warning 1
      %span.bagde.badge-warning 2
      %span.bagde.badge-warning 3

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "MaxHouse"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="favicon.ico" rel="shortcut icon")
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") MaxHouse
          .container.nav-collapse
            %ul.nav
              %li= link_to 'My Friends', "/path1"
              %li= link_to 'Help', "/path2"
              %li= link_to 'Breeds', "/path3"
            %ul.nav.pull-right
              %li= link_to 'Sign Up with Facebook', 'auth/facebook', id: 'sign_in'
    .container-fluid
      .row-fluid
        = yield
    
        %p &copy; MaxHouse@2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/welcome/index.html.haml
%h1 Welcome to Max House